development:
  adapter: sqlite3
  encoding: unicode
  database: haikus_development
  pool: 5
  username: paid_programmer

test: &test
  adapter: sqlite3
  encoding: unicode
  database: haikus_test
  pool: 5
  username: paid_programmer
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: haikus_production
  host: localhost
  pool: 5
  timeout: 5000
  username: <%= ENV["PG_USERNAME"] %>
  password: <%= ENV["PG_PASSWORD"] %>
